# Generated by Django 5.1.1 on 2024-10-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_languages_remove_user_time_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='voice',
        ),
    ]
