# Generated by Django 5.1.1 on 2024-10-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
    ]
