# Generated by Django 5.1.1 on 2024-10-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_game_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buddyrequest',
            name='slug',
        ),
    ]
