# Generated by Django 5.1.1 on 2024-10-08 14:15

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_buddyrequest_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyrequest',
            name='voice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('RaidCall', 'RaidCall'), ('Discord', 'Discord'), ('TeamSpeak', 'TeamSpeak'), ('Skype', 'Skype'), ('Ventrillo', 'Ventrillo')], max_length=200, null=True, verbose_name='Голосовые чаты'),
        ),
    ]
