# Generated by Django 5.1.1 on 2024-10-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_buddyrequest_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyrequest',
            name='prime_time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец прайм-тайма'),
        ),
        migrations.AddField(
            model_name='buddyrequest',
            name='prime_time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало прайм-тайма'),
        ),
    ]
