# Generated by Django 5.1.1 on 2024-10-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_buddyrequest_prime_time_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buddyrequest',
            name='prime_time_end',
        ),
        migrations.RemoveField(
            model_name='buddyrequest',
            name='prime_time_start',
        ),
    ]
