# Generated by Django 5.1.1 on 2024-10-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_remove_buddyrequest_prime_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyrequest',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
