# Generated by Django 5.1.1 on 2024-10-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_buddyrequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
