# Generated by Django 5.1.1 on 2024-10-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_buddyrequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyrequest',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст до'),
        ),
        migrations.AddField(
            model_name='buddyrequest',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст от'),
        ),
    ]
