# Generated by Django 5.1.1 on 2024-10-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_buddyrequest_max_age_buddyrequest_min_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyrequest',
            name='goal',
            field=models.CharField(choices=[('pro', 'про'), ('fun', 'фан')], default='fun', max_length=10, verbose_name='Цель'),
        ),
    ]
